# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: dschinkel@gmail.com
copyright_name: Your/Project/Corporate Name
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: http://dschinkel.github.io
url: "http://dschinkel.github.io"
twitter_username: daveschinkel
github_username:  dschinkel
email_username:  dschinkl@gmail.com

# Build settings
# markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
